//! Bake the character-classification tables into compile-time lookup slices:
//!
//! ```text
//! JIS_LEVELS:      codepoint -> 水準 (1..=4)
//! GAIJI_MENKUTEN:  codepoint -> (men, ku, ten)
//! KYUJI_TO_SHINJI: 旧字体/異体字 -> 新字体
//! ```
//!
//! Sources: the Project X0213 mapping table (`jisx0213-2004-std.txt`) and the
//! 常用漢字表-derived `joyo-kyujitai.tsv`.

#![allow(
    clippy::expect_used,
    reason = "build script: abort the build on missing or malformed build-time inputs"
)]

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Insert `cp → level`, keeping the most permissive (lowest) 水準.
fn upsert(map: &mut BTreeMap<u32, u8>, cp: u32, level: u8) {
    map.entry(cp)
        .and_modify(|e| {
            if level < *e {
                *e = level;
            }
        })
        .or_insert(level);
}

type LevelMap = BTreeMap<u32, u8>;
type MenKuTenMap = BTreeMap<u32, (u8, u8, u8)>;

/// Parse the Project X0213 table into (codepoint → 水準, codepoint → 面区点).
fn parse_jis(text: &str) -> (LevelMap, MenKuTenMap) {
    let mut levels: BTreeMap<u32, u8> = BTreeMap::new();
    let mut menkuten: BTreeMap<u32, (u8, u8, u8)> = BTreeMap::new();
    for line in text.lines() {
        if line.is_empty() || line.starts_with("##") {
            continue;
        }
        let mut fields = line.split('\t');
        let menku = fields.next().unwrap_or("");
        let ucs = fields.next().unwrap_or("");

        let [plane, b'-', _, _, _, _] = *menku.as_bytes() else {
            continue;
        };
        if plane != b'3' && plane != b'4' {
            continue;
        }
        let Some(rrcc_hex) = menku.get(2..6) else {
            continue;
        };
        let Ok(rrcc) = u16::from_str_radix(rrcc_hex, 16) else {
            continue;
        };
        let row = u8::try_from(rrcc >> 8).unwrap_or(0);

        // Single-codepoint "U+XXXX" only — skip combining sequences.
        let Some(hex) = ucs.strip_prefix("U+") else {
            continue;
        };
        if hex.is_empty() || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            continue;
        }
        let Ok(cp) = u32::from_str_radix(hex, 16) else {
            continue;
        };

        let ku = row.wrapping_sub(0x20);
        let level: u8 = if plane == b'4' {
            4
        } else if line.contains("[2000]") || line.contains("[2004]") {
            3
        } else if ku <= 47 {
            1
        } else {
            2
        };
        upsert(&mut levels, cp, level);

        let men = if plane == b'4' { 2u8 } else { 1u8 };
        let ten = u8::try_from(rrcc & 0x00ff).unwrap_or(0).wrapping_sub(0x20);
        menkuten.entry(cp).or_insert((men, ku, ten));

        // Full-width aliases (the ｜＃［］ markers and full-width punctuation are
        // noted via "Fullwidth: U+XXXX"); register them at the same 水準.
        // "Windows: U+XXXX" aliases are deliberately NOT registered — those are
        // the non-portable Windows variants that should surface as 機種依存文字.
        if let Some(rest) = line.split("Fullwidth: U+").nth(1) {
            let fw: String = rest.chars().take_while(char::is_ascii_hexdigit).collect();
            if let Ok(fullwidth) = u32::from_str_radix(&fw, 16) {
                upsert(&mut levels, fullwidth, level);
            }
        }
    }
    (levels, menkuten)
}

/// Parse the 旧字体・異体字 → 新字体 TSV (`old<TAB>new`, `#` comments).
fn parse_kyuji(text: &str) -> BTreeMap<u32, u32> {
    let mut kyuji = BTreeMap::new();
    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.split('\t');
        let old = cols.next().and_then(|s| s.chars().next());
        let new = cols.next().and_then(|s| s.chars().next());
        if let (Some(old), Some(new)) = (old, new) {
            kyuji.insert(u32::from(old), u32::from(new));
        }
    }
    kyuji
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set");
    let dir = Path::new(&manifest).join("data");
    println!("cargo::rerun-if-changed=data/jisx0213-2004-std.txt");
    println!("cargo::rerun-if-changed=data/joyo-kyujitai.tsv");

    let jis_text = fs::read_to_string(dir.join("jisx0213-2004-std.txt")).expect("read jisx0213");
    let kyuji_text = fs::read_to_string(dir.join("joyo-kyujitai.tsv")).expect("read kyujitai");
    let (levels, menkuten) = parse_jis(&jis_text);
    let kyuji = parse_kyuji(&kyuji_text);

    let mut out = String::with_capacity(levels.len() * 16 + menkuten.len() * 20 + 256);
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("static JIS_LEVELS: &[(u32, u8)] = &[\n");
    for (cp, level) in &levels {
        writeln!(out, "    ({cp:#06x}, {level}),").expect("write to String");
    }
    out.push_str("];\nstatic GAIJI_MENKUTEN: &[(u32, u8, u8, u8)] = &[\n");
    for (cp, (men, ku, ten)) in &menkuten {
        writeln!(out, "    ({cp:#06x}, {men}, {ku}, {ten}),").expect("write to String");
    }
    out.push_str("];\nstatic KYUJI_TO_SHINJI: &[(u32, char)] = &[\n");
    for (old, new) in &kyuji {
        writeln!(out, "    ({old:#06x}, '\\u{{{new:04x}}}'),").expect("write to String");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set");
    fs::write(Path::new(&out_dir).join("jis_tables.rs"), out).expect("write jis_tables.rs");
}
