//! Bake the Project X0213 mapping table into a sorted `char → 水準` slice.
//!
//! Source: `data/jisx0213-2004-std.txt` (JIS X 0213:2004 ↔ Unicode), whose
//! rows look like:
//!
//! ```text
//! 3-3021<TAB>U+4E9C<TAB># <cjk>                      ← plane 1, no year tag → JIS X 0208
//! 3-2E21<TAB>U+4FF1<TAB># <cjk><TAB>[2004]            ← plane 1, [2004]      → 第3水準
//! 4-2121<TAB>U+20089<TAB># <cjk><TAB>[2000]<TAB>…     ← plane 2             → 第4水準
//! ```
//!
//! Classification: plane `4-` → 第4水準; plane `3-` tagged `[2000]`/`[2004]`
//! → 第3水準; plane `3-` otherwise → JIS X 0208, split 第1 (ku ≤ 47) / 第2
//! (ku ≥ 48). The complement check (plane-1 not `[2000]`/`[2004]` = 6918
//! cells) is the verified JIS X 0208 plane-1 size.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Insert `cp → level`, keeping the most permissive (lowest) 水準 if the
/// codepoint is reached by more than one cell.
fn upsert(map: &mut BTreeMap<u32, u8>, cp: u32, level: u8) {
    map.entry(cp)
        .and_modify(|e| {
            if level < *e {
                *e = level;
            }
        })
        .or_insert(level);
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set");
    let src = Path::new(&manifest).join("data/jisx0213-2004-std.txt");
    println!("cargo::rerun-if-changed=data/jisx0213-2004-std.txt");

    let text = fs::read_to_string(&src).expect("read jisx0213-2004-std.txt");

    // codepoint → 水準 level (1..=4), keeping the most permissive (lowest).
    let mut levels: BTreeMap<u32, u8> = BTreeMap::new();

    for line in text.lines() {
        if line.is_empty() || line.starts_with("##") {
            continue;
        }
        let mut fields = line.split('\t');
        let menku = fields.next().unwrap_or("");
        let ucs = fields.next().unwrap_or("");

        // "3-RRCC" / "4-RRCC"
        let mb = menku.as_bytes();
        if mb.len() != 6 || mb[1] != b'-' {
            continue;
        }
        let plane = mb[0];
        if plane != b'3' && plane != b'4' {
            continue;
        }
        let Ok(rrcc) = u16::from_str_radix(&menku[2..6], 16) else {
            continue;
        };
        let row = u8::try_from(rrcc >> 8).unwrap_or(0);

        // Single-codepoint "U+XXXX" only — skip combining sequences.
        let Some(hex) = ucs.strip_prefix("U+") else {
            continue;
        };
        if hex.is_empty() || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            continue;
        }
        let Ok(cp) = u32::from_str_radix(hex, 16) else {
            continue;
        };

        let level: u8 = if plane == b'4' {
            4
        } else if line.contains("[2000]") || line.contains("[2004]") {
            3
        } else {
            let ku = row.wrapping_sub(0x20);
            if ku <= 47 { 1 } else { 2 }
        };

        upsert(&mut levels, cp, level);

        // Many cells map primarily to an ASCII codepoint and note their
        // full-width form via "Fullwidth: U+XXXX" — e.g. the Aozora ruby/
        // annotation markers ｜＃［］ (U+FF5C/FF03/FF3B/FF3D) and full-width
        // punctuation. Those full-width forms are what appears in real text,
        // so register them at the same 水準 as the cell. ("Windows: U+XXXX"
        // aliases are deliberately NOT registered: they are the non-portable
        // Windows variants — e.g. U+FF5E vs U+301C — that should surface as
        // 機種依存文字.)
        if let Some(rest) = line.split("Fullwidth: U+").nth(1) {
            let hex: String = rest.chars().take_while(char::is_ascii_hexdigit).collect();
            if let Ok(fullwidth) = u32::from_str_radix(&hex, 16) {
                upsert(&mut levels, fullwidth, level);
            }
        }
    }

    let mut out = String::with_capacity(levels.len() * 16 + 128);
    out.push_str("// @generated by build.rs from data/jisx0213-2004-std.txt — do not edit.\n");
    out.push_str("static JIS_LEVELS: &[(u32, u8)] = &[\n");
    for (cp, level) in &levels {
        writeln!(out, "    ({cp:#06x}, {level}),").expect("write to String");
    }
    out.push_str("];\n");

    // 旧字体・異体字 → 新字体 (derived from the 常用漢字表). One new form per old.
    let kyuji_src = Path::new(&manifest).join("data/joyo-kyujitai.tsv");
    println!("cargo::rerun-if-changed=data/joyo-kyujitai.tsv");
    let kyuji_text = fs::read_to_string(&kyuji_src).expect("read joyo-kyujitai.tsv");
    let mut kyuji: BTreeMap<u32, u32> = BTreeMap::new();
    for line in kyuji_text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.split('\t');
        let old = cols.next().and_then(|s| s.chars().next());
        let new = cols.next().and_then(|s| s.chars().next());
        if let (Some(old), Some(new)) = (old, new) {
            kyuji.insert(u32::from(old), u32::from(new));
        }
    }
    out.push_str("static KYUJI_TO_SHINJI: &[(u32, char)] = &[\n");
    for (old, new) in &kyuji {
        writeln!(out, "    ({old:#06x}, '\\u{{{new:04x}}}'),").expect("write to String");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set");
    let dest = Path::new(&out_dir).join("jis_tables.rs");
    fs::write(&dest, out).expect("write jis_tables.rs");
}
